import{S as F,a as S,i as n,b as g}from"./assets/vendor-3bbba71f.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const h of o.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&a(h)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const y="41838094-2685b6b1a22c51550e2439076",x=document.querySelector(".search-form"),b=document.querySelector(".gallery"),L=new F(".gallery a",{captionsData:"alt",captionDelay:250}),k=document.querySelector(".js-loader"),q={lines:12,length:11,width:10,radius:34,scale:1.45,corners:1,speed:.9,rotate:24,animation:"spinner-line-shrink",direction:1,color:"#ffffff",fadeColor:"transparent",top:"50%",left:"50%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner",position:"absolute"},C=new S(q);C.spin(k);const u=document.querySelector(".loader"),m=document.querySelector(".load-more");let f=1,i=0,c="",l=0;u.style.display="none";m.classList.remove("visible");x.addEventListener("submit",I);m.addEventListener("click",$);async function I(t){if(t.preventDefault(),c=t.target.elements.searchQuery.value.trim(),!c){n.warning({title:"Warning!",message:"Please enter image name!",position:"topRight",color:"#FFA000"});return}R(),E(),p();try{const e=await g.get("https://pixabay.com/api/",{params:{key:y,q:c,image_type:"photo",orientation:"horizontal",safesearch:!0,page:f,per_page:40}});d();const s=e.data;if(s.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"#EF4040"});return}i=s.totalHits,l=s.hits.length,w(s.hits),L.refresh(),n.info({message:`Congrats! We found ${i} images.`,position:"topRight",color:"#59A10D"}),i>40&&v()}catch(e){console.error("Error fetching images:",e),d(),n.error({message:"Failed to fetch images. Please try again later.",position:"topRight",color:"#EF4040"})}}function w(t){const e=document.createDocumentFragment();t.forEach(s=>{const a=P(s);e.appendChild(a)}),b.appendChild(e)}function P(t){const e=document.createElement("div");return e.classList.add("card"),e.innerHTML=`
    <a class="gallery-link" href="${t.largeImageURL}">
      <img class="card-image" src="${t.webformatURL}" alt="${t.tags}" loading="lazy">
    </a>
    <div class="card-info">
      <p class="card-text"><b>Likes:</b> ${t.likes}</p>
      <p class="card-text"><b>Views:</b> ${t.views}</p>
      <p class="card-text"><b>Comments:</b> ${t.comments}</p>
      <p class="card-text"><b>Downloads:</b> ${t.downloads}</p>
    </div>
  `,e}function R(){b.innerHTML="",f=1,p()}f++;async function $(){E(),p();try{const t=await g.get("https://pixabay.com/api/",{params:{key:y,q:c,image_type:"photo",orientation:"horizontal",safesearch:!0,page:f,per_page:40}});d();const e=t.data;if(e.hits.length===0)return;l+e.hits.length>i&&(e.hits=e.hits.slice(0,i-l)),l+=e.hits.length,w(e.hits),L.refresh(),l>=i?(p(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"#EF4040"})):v();const s=document.querySelectorAll(".card"),a=Array.from(s).slice(-40);a.length>0&&a[0].scrollIntoView({behavior:"smooth",block:"start"})}catch(t){console.error("Error fetching more images:",t),d(),n.error({message:"Failed to fetch more images. Please try again later.",position:"topRight",color:"#EF4040"})}}function E(){u.style.display="block"}function d(){u.style.display="none"}function v(){m.style.display="block"}function p(){m.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
